2022-04-21 14:41:58,632 INFO    MainThread:278571 [wandb_setup.py:_flush():71] setting env: {}
2022-04-21 14:41:58,632 INFO    MainThread:278571 [wandb_setup.py:_flush():71] setting login settings: {}
2022-04-21 14:41:58,632 INFO    MainThread:278571 [wandb_setup.py:_flush():71] setting login settings: {}
2022-04-21 14:41:58,632 INFO    MainThread:278571 [wandb_init.py:_log_setup():371] Logging user logs to /home/tbertrand/Bureau/ULM_4channel_pull/wandb/run-20220421_144158-1zbxzd4r/logs/debug.log
2022-04-21 14:41:58,632 INFO    MainThread:278571 [wandb_init.py:_log_setup():372] Logging internal logs to /home/tbertrand/Bureau/ULM_4channel_pull/wandb/run-20220421_144158-1zbxzd4r/logs/debug-internal.log
2022-04-21 14:41:58,633 INFO    MainThread:278571 [wandb_init.py:init():404] calling init triggers
2022-04-21 14:41:58,633 INFO    MainThread:278571 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-04-21 14:41:58,633 INFO    MainThread:278571 [wandb_init.py:init():460] starting backend
2022-04-21 14:41:58,633 INFO    MainThread:278571 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-21 14:41:58,646 INFO    MainThread:278571 [backend.py:ensure_launched():216] starting backend process...
2022-04-21 14:41:58,650 INFO    MainThread:278571 [backend.py:ensure_launched():221] started backend process with pid: 278626
2022-04-21 14:41:58,651 INFO    MainThread:278571 [wandb_init.py:init():469] backend started and connected
2022-04-21 14:41:58,653 INFO    MainThread:278571 [wandb_init.py:init():533] updated telemetry
2022-04-21 14:41:58,662 INFO    MainThread:278571 [wandb_init.py:init():563] communicating current version
2022-04-21 14:41:59,011 INFO    MainThread:278571 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.14 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-21 14:41:59,011 INFO    MainThread:278571 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-04-21 14:41:59,189 INFO    MainThread:278571 [wandb_init.py:init():606] starting run threads in backend
2022-04-21 14:41:59,258 INFO    MainThread:278571 [wandb_run.py:_console_start():1810] atexit reg
2022-04-21 14:41:59,258 INFO    MainThread:278571 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-04-21 14:41:59,258 INFO    MainThread:278571 [wandb_run.py:_redirect():1689] Redirecting console.
2022-04-21 14:41:59,259 INFO    MainThread:278571 [wandb_run.py:_redirect():1745] Redirects installed.
2022-04-21 14:41:59,259 INFO    MainThread:278571 [wandb_init.py:init():633] run started, returning control to user process
2022-04-21 14:42:02,301 INFO    MainThread:278571 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-04-21 14:42:02,302 INFO    MainThread:278571 [wandb_run.py:_restore():1752] restore
2022-04-21 14:42:04,797 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 950
  total_bytes: 950
}

2022-04-21 14:42:04,906 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 950
  total_bytes: 950
}

2022-04-21 14:42:05,080 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 950
  total_bytes: 950
}

2022-04-21 14:42:05,201 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 950
  total_bytes: 2286
}

2022-04-21 14:42:05,304 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 950
  total_bytes: 9023
}

2022-04-21 14:42:05,407 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}

2022-04-21 14:42:05,511 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}

2022-04-21 14:42:05,614 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}

2022-04-21 14:42:05,718 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}

2022-04-21 14:42:05,821 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}

2022-04-21 14:42:05,925 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}

2022-04-21 14:42:06,132 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}

2022-04-21 14:42:06,578 INFO    MainThread:278571 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9023
  total_bytes: 9023
}
local_info {
}

2022-04-21 14:42:07,630 INFO    MainThread:278571 [wandb_run.py:_append_files():2180] logging synced files
