/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py:352: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
   | Name           | Type            | Params
----------------------------------------------------
0  | local_max_filt | MaxPool2d       | 0
1  | encoder1       | Sequential      | 204
2  | pool1          | MaxPool2d       | 0
3  | encoder2       | Sequential      | 912
4  | pool2          | MaxPool2d       | 0
5  | encoder3       | Sequential      | 3.6 K
6  | pool3          | MaxPool2d       | 0
7  | encoder4       | Sequential      | 14.0 K
8  | pool4          | MaxPool2d       | 0
9  | bottleneck     | Sequential      | 55.7 K
10 | upconv4        | ConvTranspose2d | 8.2 K
11 | decoder4       | Sequential      | 27.8 K
12 | upconv3        | ConvTranspose2d | 2.1 K
13 | decoder3       | Sequential      | 7.0 K
14 | upconv2        | ConvTranspose2d | 520
15 | decoder2       | Sequential      | 1.8 K
16 | upconv1        | ConvTranspose2d | 132
17 | decoder1       | Sequential      | 456
18 | conv           | Conv2d          | 15
----------------------------------------------------
122 K     Trainable params
0         Non-trainable params
122 K     Total params
0.490     Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                                                                             | 0/2 [00:00<?, ?it/s]torch.Size([8, 1, 512, 512])
Traceback (most recent call last):
  File "/home/tbertrand/Bureau/ULM_4channel_pull/train.py", line 118, in <module>
    main(args,42)
  File "/home/tbertrand/Bureau/ULM_4channel_pull/train.py", line 83, in main
    trainer.fit(model,trainloader,valloader)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/tbertrand/anaconda3/envs/landmarkv2/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/tbertrand/Bureau/ULM_4channel_pull/nn/ulm_unet.py", line 225, in validation_step
    val_loss = (torch.tensor([self.penalization,1.,1.,1.])[None,:,None,None].to(self.device)*((y_hat-y))**2).mean() #l2loss(y_pred,y_true)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1