2022-04-21 14:50:26,401 INFO    MainThread:285350 [wandb_setup.py:_flush():71] setting env: {}
2022-04-21 14:50:26,401 INFO    MainThread:285350 [wandb_setup.py:_flush():71] setting login settings: {}
2022-04-21 14:50:26,402 INFO    MainThread:285350 [wandb_setup.py:_flush():71] setting login settings: {}
2022-04-21 14:50:26,402 INFO    MainThread:285350 [wandb_init.py:_log_setup():371] Logging user logs to /home/tbertrand/Bureau/ULM_4channel_pull/wandb/run-20220421_145026-38cxrue8/logs/debug.log
2022-04-21 14:50:26,402 INFO    MainThread:285350 [wandb_init.py:_log_setup():372] Logging internal logs to /home/tbertrand/Bureau/ULM_4channel_pull/wandb/run-20220421_145026-38cxrue8/logs/debug-internal.log
2022-04-21 14:50:26,402 INFO    MainThread:285350 [wandb_init.py:init():404] calling init triggers
2022-04-21 14:50:26,402 INFO    MainThread:285350 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-04-21 14:50:26,402 INFO    MainThread:285350 [wandb_init.py:init():460] starting backend
2022-04-21 14:50:26,402 INFO    MainThread:285350 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-21 14:50:26,407 INFO    MainThread:285350 [backend.py:ensure_launched():216] starting backend process...
2022-04-21 14:50:26,410 INFO    MainThread:285350 [backend.py:ensure_launched():221] started backend process with pid: 285422
2022-04-21 14:50:26,411 INFO    MainThread:285350 [wandb_init.py:init():469] backend started and connected
2022-04-21 14:50:26,413 INFO    MainThread:285350 [wandb_init.py:init():533] updated telemetry
2022-04-21 14:50:26,421 INFO    MainThread:285350 [wandb_init.py:init():563] communicating current version
2022-04-21 14:50:26,779 INFO    MainThread:285350 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.14 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-21 14:50:26,780 INFO    MainThread:285350 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-04-21 14:50:26,974 INFO    MainThread:285350 [wandb_init.py:init():606] starting run threads in backend
2022-04-21 14:50:27,044 INFO    MainThread:285350 [wandb_run.py:_console_start():1810] atexit reg
2022-04-21 14:50:27,044 INFO    MainThread:285350 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-04-21 14:50:27,044 INFO    MainThread:285350 [wandb_run.py:_redirect():1689] Redirecting console.
2022-04-21 14:50:27,045 INFO    MainThread:285350 [wandb_run.py:_redirect():1745] Redirects installed.
2022-04-21 14:50:27,045 INFO    MainThread:285350 [wandb_init.py:init():633] run started, returning control to user process
2022-04-21 14:50:27,648 INFO    MainThread:285350 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-04-21 14:50:27,649 INFO    MainThread:285350 [wandb_run.py:_restore():1752] restore
2022-04-21 14:50:30,062 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 917
  total_bytes: 917
}

2022-04-21 14:50:30,259 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 917
  total_bytes: 917
}

2022-04-21 14:50:30,994 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 917
  total_bytes: 2598
}

2022-04-21 14:50:31,097 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 917
  total_bytes: 3819
}

2022-04-21 14:50:31,201 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}

2022-04-21 14:50:31,305 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}

2022-04-21 14:50:31,408 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}

2022-04-21 14:50:31,510 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}

2022-04-21 14:50:31,613 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}

2022-04-21 14:50:31,717 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}

2022-04-21 14:50:31,900 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}

2022-04-21 14:50:32,282 INFO    MainThread:285350 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3819
  total_bytes: 3819
}
local_info {
}

2022-04-21 14:50:33,329 INFO    MainThread:285350 [wandb_run.py:_append_files():2180] logging synced files
